namespace Inventory.Application.Catalog.Products.Queries
{
    public sealed record ProductResponse(
        Guid Id,
        string Barcode,
        string NameAr,
        string NameEn,
        string? Description,
        Guid CategoryId,
        string? CategoryName,
        Guid UnitId,
        string? UnitSymbol,
        Guid? SupplierId,
        string? SupplierName,
        decimal PurchasePrice,
        decimal SellingPrice,
        decimal WholesalePrice,
        decimal QuantityInStock,
        decimal ReorderLevel,
        decimal MaxStockLevel,
        bool IsWeighable,
        bool IsActive,
        bool TrackExpiry,
        decimal TaxRate,
        string? ImageUrl,
        DateTime CreatedAt,
        DateTime? UpdatedAt,
        string BaseUnit = "قطعة",
        string? ParentUnit = "كرتونة",
        int ConversionFactor = 1,
        int ShelfLifeDays = 0,
        int ExpiryAlertDays = 3);
}
